### ISSUE TITLE
A more complex schema example.

### ISSUE THREAD

**Issue by shadyendless** [trutoo/event-bus#30]
**What is hard to understand or you feel lacks information? Please describe.**
I was wondering if there could be a more complex event schema example? I understand the basic option but I am not sure exactly which syntax is expected for more than just a single field.

**Describe your current understanding**
The documentation shows how to define an event that accepts a single basic property currently.

**Describe the improvement you'd like**
I'd like to see an event schema that takes an object with a couple of fields.

**Additional context**
If possible, it'd be nice to also get a list of which types are allowed in a schema (can we do arrays of items of a certain shape, for example).

**Comment by Swiftwork** [comment]
Thank you for your contribution. I am happy to improve the documentation. I'll try having it done by the end of this week.

**Comment by Swiftwork** [comment]
I apologize for the slow response. I think there must have been a hiccup in my notifications. I have now updated the documentation and added a more advanced test case 🚀.

Have a good week!
